import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import LenisProvider from "@/components/ui/LenisProvider";
import Footer from "@/components/ui/Footer";
import FixedSocials from "@/components/ui/SocialIcons";
import SmoothMouseTrail from "@/components/ui/SmoothMouseTrail";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${montserrat.variable} antialiased`}
      >
        <LenisProvider/>
        <SmoothMouseTrail
        size={18}
          color="rgba(247, 149, 30, 0.35)" // orange glow for United Stone branding
          smoothing={0.1}
        />
        <Navbar/>
        <FixedSocials/>
        {children}
        <Footer/>
        <LenisProvider/>
        
      </body>
    </html>
  );
}
